override:
  value: 'from application.yaml'
  
spring:
  profiles:
    include: oauth
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_ENDPOINT}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    open-in-view: false
  sql.init.mode: always

#thymeleaf
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: /templates/
    suffix: .html


  #swagger
springdoc:
  packages-to-scan: kr.ac.bokgpt
  swagger-ui:
    path: /bokgpt

# 청년 데이터
youthwelfare:
  url: https://www.youthcenter.go.kr/opi/empList.do

  client:
    serviceKey: ${YOUTH_WELFARE_SERVICEKEY}

# 중앙부처 데이터
centerwelfare:
  url: http://apis.data.go.kr/B554287/NationalWelfareInformations/NationalWelfarelist

  client:
    serviceKey: ${CENTER_WELFARE_SERVICEKEY}


# 지자체 데이터
localwelfare:
  url: http://apis.data.go.kr/B554287/LocalGovernmentWelfareInformations/LcgvWelfarelist
  detailurl: http://apis.data.go.kr/B554287/LocalGovernmentWelfareInformations/LcgvWelfaredetailed

  client:
    serviceKey: ${LOCAL_WELFARE_SERVICEKEY}





